name: "Make Yoink Installers"
on: workflow_dispatch
jobs:
  what-do-i-name-this:
    name: "Make installer (regular)"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Make regular installer
        run: |
          cd installer
          npm install
          node make -o ../installer-regular.js
          cd ..
      - name: Clone wizard generator
        uses: sudosubin/git-clone-action@v1
        with:
          repository: 'Ponali/w93-wizard-generator'
          platform: 'github'
      - name: Make Source installer
        run: |
          cd w93-wizard-generator
          node make ../ -o ../installer-source.js
      - name: Create GitHub release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          draft: true
          files: |
            installer-regular.js
            installer-source.js
