name: "Make Yoink Installers"
on: workflow_dispatch
jobs:
  what-do-i-name-this:
    name: "Make installer (regular)"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Make regular installer
        run: |
          cd installer
          npm install
          node make -o ../installer-regular.js
          cd ..
      - name: Create GitHub release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            installer-regular.js
